### PR TITLE
fix linux io.h, writing to const var, not-standard stricmp and strnicmp

### PR DESCRIPTION
**Pull request by star-tek-mb**
Not tested yet. Fixed compiling errors on Linux gcc-7.5.0.

### CODE REVIEW

**Comment by fedor4ever** [comment]
Thanks for commit but I can't accept it because:

1.  [elf2e32_next](https://github.com/fedor4ever/elf2e32_next) suprecede that crap in near future.
2. const var holds offset to start of the symbol table right after that header and must not changed. Never! If so happens E32 image is broken.
3. not-standard stricmp and strnicmp - these functions are posix conformant and therefore provided many libc
4. fix linux io.h - should be reduced

**Comment by star-tek-mb** [comment]
If i make variable const. In file **e32imagefile.cpp** line **1350** expression
```aSymInfo.iSymbolTblOffset = symSize;```
causes compilation error. Which compiler do you use?

**Comment by fedor4ever** [comment]
Mingw, mingw-64 5.x.0, 6.x.0 and more recent versions. Ms compiler works too.

**Comment by fedor4ever** [comment]
Would you so kindly to check how symplify class SymbolProcessor in elf2e32_next? It's buggy and blocks last steps to finish E32image generator and that project itself.
That task much more important than fixing near of life project.

**Comment by star-tek-mb** [comment]
Ok I will see elf2e32_next project. So Im closing PR now.

**Pull request closed without merging**
