### PR TITLE
Add CI support and renew CMakeLists

### PR DESCRIPTION
**Pull request by pent0**
- CI will run and pack artifact (elf2e32.zip).
- CMakeLists contains the file on the master branch

About the broken issue, I still compile a elf to a EPOC exe just fine, so I'm not sure what you mean :D. I will also add a CI badge for you ASAP this branch build ok.

### CODE REVIEW

**Comment by pent0** [comment]
I don't have the CI markdown link so you have to change the README yourself. Sorry :P

**Comment by fedor4ever** [comment]
Run option_dll_test.py and see yourself :steam_sad:
It build binaries but others stuff may not.
I can't control interworking Elffilesupplied with E32ImageFile. They work too cryptic for mine. Currently I wrote from scratch E32Parser with printing various info for uncompressed Symbian binaries.
Fiodar Stryzhniou

исходное сбщ
Тема: [fedor4ever/elf2e32] [WIP] Add CI support and renew CMakeLists (#2)
От: bentokun <notifications@github.com>
Дата: 09.09.2018 11.25

- CI will run and pack artifact (elf2e32.zip).
- CMakeLists contains the file on the master branch

About the broken issue, I still compile a elf to a EPOC exe just fine, so I'm not sure what you mean :D. I will also add a CI badge for you ASAP this branch build ok.
You can view, comment on, or merge this pull request online at:

  https://github.com/fedor4ever/elf2e32/pull/2

-- Commit Summary --

  * Add CI support and renew CMakeLists

-- File Changes --

    M CMakeLists.txt (20)
    A appveyor.yml (23)

-- Patch Links --

https://github.com/fedor4ever/elf2e32/pull/2.patch
https://github.com/fedor4ever/elf2e32/pull/2.diff

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/fedor4ever/elf2e32/pull/2

**Comment by fedor4ever** [comment]
Okay :) bare build not very interested without tests results.
Fiodar Stryzhniou

исходное сбщ
Тема: Re: [fedor4ever/elf2e32] Add CI support and renew CMakeLists (#2)
От: bentokun <notifications@github.com>
Дата: 09.09.2018 11.56

I don't have the CI markdown link so you have to change the README yourself. Sorry :P

**Comment by pent0** [comment]
Yeah, you can add the test to appveyor script, i don't really know how, so currently the CI may just use for PR testing (and decorator too :)) Thanks

Wish you luck writing E32Parser :). The original source code was a cryptic mess (but it still better than old tool that uses unportable variable type and Windows function lol)

**Comment by fedor4ever** [comment]
HI! Can you pack CI commits in one commit and push again? I wil reset repo till commit 8210dfa5c31d230db3f034d593a16af8f60faa65. Repo history looks bad with commits that fix previous =(
E32 parser will complete after two days. After that time I reset my repo and pack your changes myself.

Anyway I should finish digging in that crap asap and write looong story about =).

**Comment by pent0** [comment]
This is already merged so it's now from your side to rebase it, this PR don't effect on master anymore. Sorry :P You should have told me before.

And ok, keep up the good work!

**Comment by fedor4ever** [comment]
Use git -reset on your repo. Do not choose hard suboption or all changes after commit will be lost.
Make copy you repo before reset not after :)
I do same from my side.
Fiodar Stryzhniou

исходное сбщ
Тема: Re: [fedor4ever/elf2e32] Add CI support and renew CMakeLists (#2)
От: bentokun <notifications@github.com>
Дата: 13.09.2018 20.36

I think you have to rebase the whole repo. This is already merged so it's now from your side to rebase it. Sorry :P

**Comment by fedor4ever** [comment]
Repo was reset. Please pack your changes in one commit.

**Comment by pent0** [comment]
Ok, i will rebase and open a new PR

**Pull request merged**
