### PR TITLE
Fix total of characters do delete in ParseLibPaths

### PR DESCRIPTION
**Pull request by pent0**
We need to also delete the semicolon

### CODE REVIEW

**Comment by fedor4ever** [comment]
There some problems with it? How to call them?

**Comment by pent0** [comment]
Call what ?

**Comment by fedor4ever** [comment]
What problems does it cause? How them see? I have much more serious problem - incorrect .dso generation. Them twice bigger than should be.

**Comment by pent0** [comment]
For example:

C:\Thu\lib2;C:\Thu\koo

Original implementation, only takes and delete c:\thu\lib2, leaving ";C:\Thu\koo". Path are messed startng from this

**Comment by fedor4ever** [comment]
Merged.

**Pull request merged**
